//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Finance
{
    public partial class PendingFinanceSetup
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsgOk;
        protected global::System.Web.UI.WebControls.Literal litMsgOk;
        protected global::System.Web.UI.WebControls.Panel pnlMsgErr;
        protected global::System.Web.UI.WebControls.Label lblMsgErr;

        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litReady;
        protected global::System.Web.UI.WebControls.Literal litMissing;
        protected global::System.Web.UI.WebControls.Literal litCompleted;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlShift;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnApply;
        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.Repeater rptQueue;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Label lblPageInfo;
        protected global::System.Web.UI.WebControls.Button btnPrev;
        protected global::System.Web.UI.WebControls.Button btnNext;

        protected global::System.Web.UI.WebControls.Panel pnlConfirm;
        protected global::System.Web.UI.WebControls.Label lblCsName;
        protected global::System.Web.UI.WebControls.Label lblCsCode;
        protected global::System.Web.UI.WebControls.Label lblCsYear;
        protected global::System.Web.UI.WebControls.Label lblCsClassSection;
        protected global::System.Web.UI.WebControls.Label lblCsShift;
        protected global::System.Web.UI.WebControls.Repeater rptPreview;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.Literal litPreviewTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfStudentId;
        protected global::System.Web.UI.WebControls.Button btnCancelConfirm;
        protected global::System.Web.UI.WebControls.Button btnConfirmCreate;
    }
}
