//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class CreateExamination
    {
        protected global::System.Web.UI.WebControls.Literal litCrumb;
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlScope;
        protected global::System.Web.UI.WebControls.Panel pnlSubjects;
        protected global::System.Web.UI.WebControls.CheckBoxList cblSubjects;
        protected global::System.Web.UI.WebControls.Panel pnlNoSubjects;
        protected global::System.Web.UI.WebControls.TextBox txtPass;
        protected global::System.Web.UI.WebControls.TextBox txtTotal;
        protected global::System.Web.UI.WebControls.TextBox txtWeight;
        protected global::System.Web.UI.WebControls.Button btnDraft;
        protected global::System.Web.UI.WebControls.Button btnCreate;

        protected global::System.Web.UI.WebControls.Literal ovName;
        protected global::System.Web.UI.WebControls.Literal ovYear;
        protected global::System.Web.UI.WebControls.Literal ovTerm;
        protected global::System.Web.UI.WebControls.Literal ovType;
        protected global::System.Web.UI.WebControls.Literal ovDuration;
        protected global::System.Web.UI.WebControls.Literal ovStatus;
        protected global::System.Web.UI.WebControls.Literal ovClass;
        protected global::System.Web.UI.WebControls.Literal ovSubjects;
    }
}
