//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class ExaminationDetails
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlBody;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.HyperLink lnkEdit;
        protected global::System.Web.UI.WebControls.HyperLink lnkSchedule;
        protected global::System.Web.UI.WebControls.HyperLink lnkMarks;
        protected global::System.Web.UI.WebControls.HyperLink lnkResults;
        protected global::System.Web.UI.WebControls.Button btnActivate;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litYear;
        protected global::System.Web.UI.WebControls.Literal litTerm;
        protected global::System.Web.UI.WebControls.Literal litDuration;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litPass;
        protected global::System.Web.UI.WebControls.Literal litWeight;
        protected global::System.Web.UI.WebControls.Literal litCreatedBy;
        protected global::System.Web.UI.WebControls.GridView gvSubjects;
        protected global::System.Web.UI.WebControls.Literal litScope;
        protected global::System.Web.UI.WebControls.Literal litSchedule;
        protected global::System.Web.UI.WebControls.Literal litMarks;
        protected global::System.Web.UI.WebControls.Literal litPublication;
    }
}
