//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class Examinations
    {
        protected global::System.Web.UI.WebControls.Button btnPublish;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litUpcoming;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litPublished;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.GridView gvExams;
        protected global::System.Web.UI.WebControls.GridView gvRooms;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
