//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class ExamSchedule
    {
        protected global::System.Web.UI.WebControls.Button btnPublish;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Literal litTotalExams;
        protected global::System.Web.UI.WebControls.Literal litScheduled;
        protected global::System.Web.UI.WebControls.Literal litInvigilators;
        protected global::System.Web.UI.WebControls.Literal litRooms;
        protected global::System.Web.UI.WebControls.DropDownList ddlFYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlFTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlFExam;
        protected global::System.Web.UI.WebControls.DropDownList ddlFStatus;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.DropDownList ddlExam;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlRoom;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.DropDownList ddlInvigilator;
        protected global::System.Web.UI.WebControls.Panel pnlCapacity;
        protected global::System.Web.UI.WebControls.Literal litCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}
