//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class MarksEntry
    {
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.Button btnSaveDraft;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Button btnReopen;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litEntered;
        protected global::System.Web.UI.WebControls.Literal litRemaining;
        protected global::System.Web.UI.WebControls.Literal litCompletion;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlExam;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Literal litLockNote;
        protected global::System.Web.UI.WebControls.GridView gvMarks;
        protected global::System.Web.UI.WebControls.GridView gvScale;
        protected global::System.Web.UI.WebControls.Literal litSumTotal;
        protected global::System.Web.UI.WebControls.Literal litSumEntered;
        protected global::System.Web.UI.WebControls.Literal litSumSubmitted;
        protected global::System.Web.UI.WebControls.Literal litReady;
    }
}
