//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class ReportCard
    {
        protected global::System.Web.UI.WebControls.Panel pnlDenied;
        protected global::System.Web.UI.WebControls.Panel pnlBody;
        protected global::System.Web.UI.WebControls.Literal litExam;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litCode;
        protected global::System.Web.UI.WebControls.Literal litAdm;
        protected global::System.Web.UI.WebControls.Literal litClass;
        protected global::System.Web.UI.WebControls.Literal litYear;
        protected global::System.Web.UI.WebControls.Literal litTerm;
        protected global::System.Web.UI.WebControls.Repeater rptSubjects;
        protected global::System.Web.UI.WebControls.Literal litObtained;
        protected global::System.Web.UI.WebControls.Literal litMax;
        protected global::System.Web.UI.WebControls.Literal litAvg;
        protected global::System.Web.UI.WebControls.Literal litGrade;
        protected global::System.Web.UI.WebControls.Literal litRank;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litPublished;
    }
}
