//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Examinations
{
    public partial class Transcripts
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.Label lblYearOpt;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl wrapTerm;
        protected global::System.Web.UI.WebControls.Label lblTermOpt;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudent;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnFind;
        protected global::System.Web.UI.WebControls.Button btnLoad;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Literal litDoc;
    }
}
