using System;using System.Data;using System.Linq;using System.Web.UI.WebControls;
namespace AQOONHUB_SMS.Modules.Reports{public partial class CustomReportBuilder:ReportStage5Base{
 int SavedId{get{int id;return int.TryParse(Request.QueryString["saved"],out id)?id:0;}}
 protected void Page_Load(object sender,EventArgs e){if(!Require(ReportAuthorization.CustomBuilder))return;if(!IsPostBack){BindSources();BindFields();if(SavedId>0)LoadSaved();}}
 void BindSources(){ddlSource.Items.Clear();foreach(var s in ReportBuilderMetadata.ForRole(CurrentRole))ddlSource.Items.Add(new ListItem(s.Name,s.Key));}
 void BindFields(){var s=ReportBuilderMetadata.Resolve(ddlSource.SelectedValue);cblFields.Items.Clear();ddlFilterField.Items.Clear();ddlSort.Items.Clear();if(s==null)return;foreach(var f in s.Fields){cblFields.Items.Add(new ListItem(f.Label,f.Key));ddlFilterField.Items.Add(new ListItem(f.Label,f.Key));ddlSort.Items.Add(new ListItem(f.Label,f.Key));}ddlOrientation.SelectedValue=s.Orientation;BindOperators();}
 void LoadSaved(){var r=Repo.GetSavedReport(SavedId);if(r==null){Message("Saved report was not found.",false);return;}int owner=r["OwnerUserID"]==DBNull.Value?0:Convert.ToInt32(r["OwnerUserID"]);string vis=Convert.ToString(r["Visibility"]);if(owner!=CurrentUserId&&!ReportAuthorization.IsStage5Admin(CurrentRole)&&vis=="Private"){Message("Saved report is unavailable or unauthorized.",false);return;}var v=ReportBuilderMetadata.Validate(Convert.ToString(r["ConfigurationJson"]),CurrentRole);if(!v.Valid){Message("Saved report configuration is invalid or no longer authorized.",false);return;}ddlSource.SelectedValue=v.Source.Key;BindFields();foreach(ListItem x in cblFields.Items)x.Selected=v.Config.columns.Contains(x.Value);txtTitle.Text=Convert.ToString(r["ReportName"]);ddlOrientation.SelectedValue=v.Config.orientation;ddlVisibility.SelectedValue=vis;if(v.Config.sort!=null){ddlSort.SelectedValue=v.Config.sort.field;ddlDirection.SelectedValue=v.Config.sort.direction;}if(v.Config.filters.Length>0){ddlFilterField.SelectedValue=v.Config.filters[0].field;BindOperators();ddlOperator.SelectedValue=v.Config.filters[0].@operator;txtValue.Text=v.Config.filters[0].value;}var d=ReportBuilderMetadata.Execute(Repo,v,ReportBuilderMetadata.PreviewLimit);BindPreview(d,"Validated saved configuration");Repo.MarkSavedRun(SavedId);Audit("Generated",Convert.ToString(r["ReportKey"]),Convert.ToString(r["ReportName"]),Convert.ToString(r["Category"]));}
 protected void ddlSource_Changed(object o,EventArgs e){BindFields();}protected void ddlFilterField_Changed(object o,EventArgs e){BindOperators();}
 void BindOperators(){ddlOperator.Items.Clear();var s=ReportBuilderMetadata.Resolve(ddlSource.SelectedValue);var f=s==null?null:s.Fields.FirstOrDefault(x=>x.Key==ddlFilterField.SelectedValue);if(f!=null)foreach(string x in f.Operators)ddlOperator.Items.Add(new ListItem(x.Replace('-',' '),x));}
 BuilderConfig Config(){var cols=cblFields.Items.Cast<ListItem>().Where(x=>x.Selected).Select(x=>x.Value).ToArray();bool noValue=string.IsNullOrWhiteSpace(txtValue.Text)&&ddlOperator.SelectedValue!="is-empty"&&ddlOperator.SelectedValue!="is-not-empty";var filters=noValue?new BuilderFilter[0]:new[]{new BuilderFilter{field=ddlFilterField.SelectedValue,@operator=ddlOperator.SelectedValue,value=txtValue.Text.Trim()}};return new BuilderConfig{version=1,sourceKey=ddlSource.SelectedValue,columns=cols,filters=filters,groupBy=new string[0],sort=new BuilderSort{field=ddlSort.SelectedValue,direction=ddlDirection.SelectedValue},summaries=new string[0],chart=null,orientation=ddlOrientation.SelectedValue};}
 BuilderValidation ValidateConfig(){return ReportBuilderMetadata.Validate(ReportBuilderMetadata.Serialize(Config()),CurrentRole);}
 void BindPreview(DataTable d,string filter){gvPreview.DataSource=d;gvPreview.DataBind();string when=DateTime.Now.ToString("dd MMM yyyy HH:mm");litSummary.Text="<span class='text-xs text-gray-500'>"+d.Rows.Count+" row(s) · "+ReportUi.Enc(filter)+" · Generated "+when+"</span>";litPrintTitle.Text=ReportUi.Enc(TitleValue());litPrintMeta.Text="<div class='text-xs'>"+ReportUi.Enc(filter)+" · Generated "+when+"</div>";litPageCss.Text="<style>@media print{@page{size:A4 "+ddlOrientation.SelectedValue.ToLowerInvariant()+";margin:10mm}}</style>";}
 DataTable Preview(){var v=ValidateConfig();if(!v.Valid){Message(v.Message,false);return null;}var d=Repo.PreviewBuilder(v);BindPreview(d,"Approved builder filters");Audit("Custom Report Previewed",v.Source.Key,TitleValue(),v.Source.Category);return d;}
 string TitleValue(){return string.IsNullOrWhiteSpace(txtTitle.Text)?"Custom Report":txtTitle.Text.Trim();}
 protected void btnPreview_Click(object o,EventArgs e){Preview();}
 protected void btnSave_Click(object o,EventArgs e){var v=ValidateConfig();if(!v.Valid){Message(v.Message,false);return;}bool restricted=v.Source.Fields.Any(f=>f.Sensitive&&v.Config.columns.Contains(f.Key));if(!ReportAuthorization.CanCreateVisibility(CurrentRole,ddlVisibility.SelectedValue,restricted)){Message("The selected visibility is not permitted.",false);return;}int id=Repo.CreateSavedReport(TitleValue(),v.Source.Key,v.Source.Category,ReportBuilderMetadata.Serialize(v.Config),ddlVisibility.SelectedValue,CurrentUserId);Audit("Saved Report Created",v.Source.Key,TitleValue(),v.Source.Category);Message("Report saved securely (#"+id+").",true);}
 protected void btnExport_Click(object o,EventArgs e){var v=ValidateConfig();if(!v.Valid){Message(v.Message,false);return;}var d=ReportBuilderMetadata.Execute(Repo,v,v.Source.ExportLimit);string key=SavedId>0?"saved-"+SavedId:"custom-"+v.Source.Key;var def=new ReportDefinition(key,TitleValue(),v.Source.Category,v.Source.Handler,"Custom report",v.Config.orientation,new string[0],false,true);new ReportExportService(Repo).Export(Response,def,d,CurrentUserId,"Approved builder filters",Ip());}
 protected void btnReset_Click(object o,EventArgs e){Response.Redirect("CustomReportBuilder.aspx");}
 void Message(string m,bool ok){litMessage.Text="<div role='alert' class='s5-msg "+(ok?"s5-ok":"s5-error")+"'>"+ReportUi.Enc(m)+"</div>";}
}}
