<%@ Page Title="Performance Analytics | AQOONHUB SMS" Language="C#" MasterPageFile="~/MasterPages/MainMaster.master" AutoEventWireup="true" CodeBehind="PerformanceAnalytics.aspx.cs" Inherits="AQOONHUB_SMS.Modules.Reports.PerformanceAnalytics" %>
<asp:Content ID="h" ContentPlaceHolderID="head" runat="server"><style>
.a-wrap{padding:1.25rem;max-width:1600px;margin:auto}.filters{display:grid;grid-template-columns:1fr;gap:.75rem}.filters label{display:block;font-size:.72rem;font-weight:700;margin-bottom:.3rem}.filters select{width:100%;min-height:44px}.summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.metric{padding:1rem}.metric .k{font-size:.68rem;text-transform:uppercase;font-weight:700;color:#64748b}.metric .v{font-size:1.35rem;font-weight:800;margin-top:.2rem}.charts{display:grid;grid-template-columns:1fr;gap:1rem}.chart{padding:1rem;min-width:0}.chartbox{height:280px;position:relative}.chart h2{font-size:.9rem;font-weight:750;margin-bottom:.75rem}.empty{height:240px;display:flex;align-items:center;justify-content:center;text-align:center;color:#64748b;font-size:.8rem;padding:1rem}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{padding:.7rem;text-align:left;border-bottom:1px solid #e2e8f0;white-space:nowrap;font-size:.78rem}.tbl th{font-size:.68rem;text-transform:uppercase;color:#64748b}.scroll{overflow-x:auto;max-width:100%}.dark .tbl th,.dark .tbl td{border-color:#263449}.focusable:focus-visible{outline:3px solid #93c5fd;outline-offset:2px}
@media(min-width:640px){.filters{grid-template-columns:repeat(2,1fr)}}@media(min-width:768px){.summary{grid-template-columns:repeat(4,1fr)}}@media(min-width:1100px){.filters{grid-template-columns:repeat(5,1fr)}.charts{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
.dark .filters select{background:#172033!important;color:#e2e8f0!important;border-color:#475569!important}.dark .empty{color:#a8b6ca}
</style></asp:Content>
<asp:Content ID="b" ContentPlaceHolderID="MainContent" runat="server"><main class="a-wrap">
<nav class="flex gap-1.5 text-xs text-gray-500 dark:text-slate-400 mb-2" aria-label="Breadcrumb"><a href="~/Modules/Reports/Reports.aspx" runat="server">Reports</a><span>/</span><span>Performance Analytics</span></nav>
<div class="mb-4"><h1 class="text-xl md:text-2xl font-bold">Performance Analytics</h1><p class="text-sm text-gray-500 dark:text-slate-400 mt-1">Published examination snapshots and official attendance records.</p></div>
<section class="card p-4 mb-4" aria-labelledby="filterTitle"><h2 id="filterTitle" class="text-sm font-bold mb-3">Analytics filters</h2><div class="filters"><div><label for="<%=ddlYear.ClientID%>">Academic year</label><asp:DropDownList ID="ddlYear" runat="server" CssClass="form-select focusable" AutoPostBack="true" OnSelectedIndexChanged="ddlYear_Changed" /></div><div><label for="<%=ddlTerm.ClientID%>">Term</label><asp:DropDownList ID="ddlTerm" runat="server" CssClass="form-select focusable" /></div><div><label for="<%=ddlExam.ClientID%>">Examination</label><asp:DropDownList ID="ddlExam" runat="server" CssClass="form-select focusable" /></div><div><label for="<%=ddlClass.ClientID%>">Class</label><asp:DropDownList ID="ddlClass" runat="server" CssClass="form-select focusable" AutoPostBack="true" OnSelectedIndexChanged="ddlClass_Changed" /></div><div><label for="<%=ddlSection.ClientID%>">Section</label><asp:DropDownList ID="ddlSection" runat="server" CssClass="form-select focusable" /></div></div><div class="flex flex-wrap gap-2 mt-4"><asp:Button ID="btnApply" runat="server" Text="Apply filters" CssClass="btn btn-primary min-h-[44px]" OnClick="btnApply_Click"/><asp:Button ID="btnReset" runat="server" Text="Reset" CssClass="btn btn-secondary min-h-[44px]" OnClick="btnReset_Click" CausesValidation="false"/></div></section>
<asp:Panel ID="pnlError" runat="server" Visible="false" CssClass="card p-4 mb-4 text-sm text-amber-700 dark:text-amber-300" role="alert"><asp:Literal ID="litError" runat="server" /></asp:Panel>
<section class="summary mb-4" aria-label="Performance summary"><% foreach(string id in new[]{"Average performance","Pass rate","Failure rate","Total students","At-risk students"}) { %><% } %><div class="card metric"><p class="k">Average performance</p><p class="v"><asp:Literal ID="litAverage" runat="server" /></p></div><div class="card metric"><p class="k">Pass rate</p><p class="v text-emerald-600"><asp:Literal ID="litPass" runat="server" /></p></div><div class="card metric"><p class="k">Failure rate</p><p class="v text-amber-600"><asp:Literal ID="litFail" runat="server" /></p></div><div class="card metric"><p class="k">Total students</p><p class="v"><asp:Literal ID="litStudents" runat="server" /></p></div><div class="card metric"><p class="k">At-risk students</p><p class="v text-red-600"><asp:Literal ID="litRisk" runat="server" /></p></div></section>
<section class="charts mb-4"><asp:Repeater ID="rptCharts" runat="server"><ItemTemplate><article class="card chart"><h2><%# Eval("Title") %></h2><asp:PlaceHolder runat="server" Visible='<%# Convert.ToBoolean(Eval("HasData")) %>'><div class="chartbox"><canvas id='<%# Eval("CanvasId") %>' role="img" aria-label='<%# Eval("AriaLabel") %>'></canvas></div></asp:PlaceHolder><asp:PlaceHolder runat="server" Visible='<%# !Convert.ToBoolean(Eval("HasData")) %>'><div class="empty" role="status"><%# Eval("EmptyMessage") %></div></asp:PlaceHolder></article></ItemTemplate></asp:Repeater></section>
<section class="card overflow-hidden"><div class="p-4 border-b dark:border-slate-700"><h2 class="text-sm font-bold">At-risk students</h2><p class="text-xs text-gray-500 mt-1">Indicators use published results and official submitted/locked attendance.</p></div><div class="scroll"><asp:GridView ID="gvRisk" runat="server" AutoGenerateColumns="true" GridLines="None" CssClass="tbl"><EmptyDataTemplate><div class="empty">No at-risk students were found for this published scope.</div></EmptyDataTemplate></asp:GridView></div></section>
</main><script src='<%= ResolveUrl("~/Assets/js/plugins/chart.js?v=4.4.7") %>'></script><asp:Literal ID="litChartData" runat="server"/><script>
(function(){if(typeof Chart==='undefined'||!window.AQHAnalytics)return;var charts={};var dark=document.documentElement.classList.contains('dark');var fg=dark?'#cbd5e1':'#475569',grid=dark?'rgba(148,163,184,.18)':'rgba(100,116,139,.16)';window.AQHAnalytics.forEach(function(c){var el=document.getElementById(c.id);if(!el)return;if(charts[c.id])charts[c.id].destroy();charts[c.id]=new Chart(el,{type:c.type,data:c.data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:fg}},tooltip:{backgroundColor:dark?'#182235':'#0f172a'}},scales:c.type==='doughnut'?{}:{x:{ticks:{color:fg},grid:{color:grid}},y:{beginAtZero:true,ticks:{color:fg},grid:{color:grid}}}}});});})();
</script></asp:Content>
