//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Reports
{
    public partial class Reports
    {
        protected global::System.Web.UI.WebControls.Button btnRefresh;
        protected global::System.Web.UI.WebControls.HyperLink lnkCustom;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litToday;
        protected global::System.Web.UI.WebControls.Literal litSaved;
        protected global::System.Web.UI.WebControls.Literal litScheduled;
        protected global::System.Web.UI.WebControls.Literal litExports;
        protected global::System.Web.UI.WebControls.Literal litCategories;
        protected global::System.Web.UI.WebControls.Panel pnlChart;
        protected global::System.Web.UI.WebControls.Panel pnlChartEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptMostUsed;
        protected global::System.Web.UI.WebControls.Panel pnlMostUsedEmpty;
        protected global::System.Web.UI.WebControls.Literal litCategoryCards;
        protected global::System.Web.UI.WebControls.GridView gvActivity;
        protected global::System.Web.UI.WebControls.GridView gvSources;
        protected global::System.Web.UI.WebControls.GridView gvExports;
        protected global::System.Web.UI.WebControls.GridView gvScheduled;
        protected global::System.Web.UI.WebControls.Literal litChartData;
    }
}
