//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Reports
{
    public partial class ReportViewer
    {
        protected global::System.Web.UI.WebControls.Literal litPageCss;
        protected global::System.Web.UI.WebControls.HyperLink lnkCategory;
        protected global::System.Web.UI.WebControls.Literal litCrumb;
        protected global::System.Web.UI.WebControls.Panel pnlInvalid;
        protected global::System.Web.UI.WebControls.Literal litInvalid;
        protected global::System.Web.UI.WebControls.Panel pnlReport;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litDesc;
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Panel pnlFilters;
        protected global::System.Web.UI.WebControls.Panel fYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.Panel fTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.Panel fClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.Panel fSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.Panel fSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.Panel fExam;
        protected global::System.Web.UI.WebControls.DropDownList ddlExam;
        protected global::System.Web.UI.WebControls.Panel fPeriod;
        protected global::System.Web.UI.WebControls.DropDownList ddlPeriod;
        protected global::System.Web.UI.WebControls.Panel fTeacher;
        protected global::System.Web.UI.WebControls.DropDownList ddlTeacher;
        protected global::System.Web.UI.WebControls.Panel fStudent;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudent;
        protected global::System.Web.UI.WebControls.Panel fDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlDept;
        protected global::System.Web.UI.WebControls.Panel fGender;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.Panel fStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Panel fFrom;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.Panel fTo;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.Panel fSearch;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Literal litPrintTitle;
        protected global::System.Web.UI.WebControls.Literal litSummary;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}
