using System;using System.Data;
namespace AQOONHUB_SMS.Modules.Reports
{public sealed partial class ReportsRepository{
 public DataTable GetSchedules(int uid,string role){return ExecuteDataTable(@"SELECT q.ScheduledReportID,q.SavedReportID,s.ReportName,q.Frequency,CONVERT(varchar(5),q.RunTime,108) RunTime,q.DayOfWeek,q.DayOfMonth,q.Recipients,q.ExportFormat,q.Status,q.LastRunAt,q.NextRunAt,COALESCE(u.FullName,'System') CreatedBy,q.CreatedAt FROM ScheduledReports q JOIN SavedReports s ON s.SavedReportID=q.SavedReportID LEFT JOIN Users u ON u.UserID=q.CreatedBy WHERE (@admin=1 OR q.CreatedBy=@uid) ORDER BY q.CreatedAt DESC",new[]{P("@admin",ReportAuthorization.IsStage5Admin(role)),P("@uid",uid)});}
 public DataRow GetSchedule(int id,int uid,string role){var d=ExecuteDataTable("SELECT TOP 1 q.ScheduledReportID,q.SavedReportID,q.Frequency,q.RunTime,q.DayOfWeek,q.DayOfMonth,q.Recipients,q.ExportFormat,q.Status,q.LastRunAt,q.NextRunAt,q.CreatedBy,q.CreatedAt,q.UpdatedAt FROM dbo.ScheduledReports q WHERE q.ScheduledReportID=@id AND (q.CreatedBy=@u OR @admin=1)",new[]{P("@id",id),P("@u",uid),P("@admin",ReportAuthorization.IsStage5Admin(role))});return d.Rows.Count==0?null:d.Rows[0];}
 public int CreateSchedule(int savedId,string frequency,TimeSpan time,int? dow,int? dom,string recipients,string format,DateTime next,int uid){object o=ExecuteScalar(@"INSERT ScheduledReports(SavedReportID,Frequency,RunTime,DayOfWeek,DayOfMonth,Recipients,ExportFormat,Status,NextRunAt,CreatedBy,CreatedAt)VALUES(@s,@f,@t,@w,@m,@r,@x,'Pending Scheduler Configuration',@n,@u,GETDATE());SELECT SCOPE_IDENTITY()",new[]{P("@s",savedId),P("@f",frequency),P("@t",time),P("@w",(object)dow??DBNull.Value),P("@m",(object)dom??DBNull.Value),P("@r",recipients),P("@x",format),P("@n",next),P("@u",uid)});return Convert.ToInt32(o);}
 public bool UpdateSchedule(int id,int savedId,string frequency,TimeSpan time,int? dow,int? dom,string recipients,string format,DateTime next,int uid,string role){if(GetSchedule(id,uid,role)==null)return false;ExecuteNonQuery(@"UPDATE ScheduledReports SET SavedReportID=@s,Frequency=@f,RunTime=@t,DayOfWeek=@w,DayOfMonth=@m,Recipients=@r,ExportFormat=@x,Status='Pending Scheduler Configuration',NextRunAt=@n,LastRunAt=NULL,UpdatedAt=GETDATE() WHERE ScheduledReportID=@id",new[]{P("@id",id),P("@s",savedId),P("@f",frequency),P("@t",time),P("@w",(object)dow??DBNull.Value),P("@m",(object)dom??DBNull.Value),P("@r",recipients),P("@x",format),P("@n",next)});return true;}
 public bool SetScheduleEnabled(int id,bool enabled,DateTime next,int uid,string role){if(GetSchedule(id,uid,role)==null)return false;ExecuteNonQuery("UPDATE ScheduledReports SET Status=@s,NextRunAt=@n,LastRunAt=NULL,UpdatedAt=GETDATE() WHERE ScheduledReportID=@id",new[]{P("@id",id),P("@s",enabled?"Pending Scheduler Configuration":"Disabled"),P("@n",enabled?(object)next:DBNull.Value)});return true;}
 public bool DeleteSchedule(int id,int uid,string role){if(GetSchedule(id,uid,role)==null)return false;ExecuteNonQuery("DELETE ScheduledReports WHERE ScheduledReportID=@id",new[]{P("@id",id)});return true;}
}}
