using System;using System.Data;using System.Web.UI.WebControls;
namespace AQOONHUB_SMS.Modules.Reports{public partial class ScheduledReports:ReportStage5Base{
 protected void Page_Load(object o,EventArgs e){if(!Require(ReportAuthorization.Scheduled))return;if(!IsPostBack){BindReports();Bind();}}
 void BindReports(){ddlReport.Items.Clear();foreach(DataRow r in Repo.GetSavedReports(CurrentUserId,CurrentRole).Rows)if(Convert.ToString(r["Status"])=="Active")ddlReport.Items.Add(new ListItem(Convert.ToString(r["ReportName"]),Convert.ToString(r["SavedReportID"])));}
 void Bind(){gv.DataSource=Repo.GetSchedules(CurrentUserId,CurrentRole);gv.DataBind();}
 public static DateTime Next(string f,TimeSpan t,int? day,DateTime now){DateTime n=now.Date.Add(t);if(n<=now)n=n.AddDays(1);if(f=="Weekly"){int target=day??1;while((int)n.DayOfWeek!=target)n=n.AddDays(1);}else if(f=="Monthly"){int d=Math.Max(1,Math.Min(day??1,DateTime.DaysInMonth(n.Year,n.Month)));n=new DateTime(n.Year,n.Month,d).Add(t);if(n<=now){var x=n.AddMonths(1);n=new DateTime(x.Year,x.Month,Math.Min(d,DateTime.DaysInMonth(x.Year,x.Month))).Add(t);}}else if(f=="Termly")n=n.AddMonths(4);else if(f=="Yearly")n=n.AddYears(1);return n;}
 bool Values(out int savedId,out TimeSpan time,out int? day,out DateTime next,out DataRow saved){savedId=0;time=TimeSpan.Zero;saved=null;next=DateTime.MinValue;day=null;if(!int.TryParse(ddlReport.SelectedValue,out savedId)||!TimeSpan.TryParse(txtTime.Text,out time)){Msg("Select a saved report and valid time.",false);return false;}saved=Repo.GetSavedReport(savedId);if(saved==null){Msg("Saved report is unavailable.",false);return false;}int owner=saved["OwnerUserID"]==DBNull.Value?0:Convert.ToInt32(saved["OwnerUserID"]);string vis=Convert.ToString(saved["Visibility"]);if(owner!=CurrentUserId&&!ReportAuthorization.IsStage5Admin(CurrentRole)&&vis=="Private"){Msg("You cannot schedule this report.",false);return false;}int x;if(int.TryParse(txtDay.Text,out x))day=x;if(ddlFrequency.SelectedValue=="Weekly"&&(!day.HasValue||day<0||day>6)||ddlFrequency.SelectedValue=="Monthly"&&(!day.HasValue||day<1||day>31)){Msg("Day is invalid for the selected frequency.",false);return false;}next=Next(ddlFrequency.SelectedValue,time,day,DateTime.Now);return true;}
 protected void btnSave_Click(object o,EventArgs e){int savedId;TimeSpan time;int? day;DateTime next;DataRow saved;if(!Values(out savedId,out time,out day,out next,out saved))return;int editId;bool editing=int.TryParse(hidEditId.Value,out editId)&&editId>0;bool ok=editing?Repo.UpdateSchedule(editId,savedId,ddlFrequency.SelectedValue,time,ddlFrequency.SelectedValue=="Weekly"?day:null,ddlFrequency.SelectedValue=="Monthly"?day:null,txtRecipients.Text.Trim(),ddlFormat.SelectedValue,next,CurrentUserId,CurrentRole):Repo.CreateSchedule(savedId,ddlFrequency.SelectedValue,time,ddlFrequency.SelectedValue=="Weekly"?day:null,ddlFrequency.SelectedValue=="Monthly"?day:null,txtRecipients.Text.Trim(),ddlFormat.SelectedValue,next,CurrentUserId)>0;if(!ok){Msg("Schedule update was denied.",false);return;}Audit(editing?"Schedule Updated":"Schedule Created",Convert.ToString(saved["ReportKey"]),Convert.ToString(saved["ReportName"]),Convert.ToString(saved["Category"]));ResetForm();Msg("Schedule saved as Pending Scheduler Configuration.",true);Bind();}
 protected void btnCancel_Click(object o,EventArgs e){ResetForm();}
 protected void gv_RowCommand(object o,GridViewCommandEventArgs e){int id;if(!int.TryParse(Convert.ToString(e.CommandArgument),out id))return;var row=Repo.GetSchedule(id,CurrentUserId,CurrentRole);if(row==null){Msg("Schedule is unavailable or unauthorized.",false);return;}if(e.CommandName=="EditSchedule"){hidEditId.Value=id.ToString();ddlReport.SelectedValue=Convert.ToString(row["SavedReportID"]);ddlFrequency.SelectedValue=Convert.ToString(row["Frequency"]);txtTime.Text=row["RunTime"]==DBNull.Value?"08:00":((TimeSpan)row["RunTime"]).ToString(@"hh\:mm");txtDay.Text=row["DayOfWeek"]!=DBNull.Value?Convert.ToString(row["DayOfWeek"]):row["DayOfMonth"]!=DBNull.Value?Convert.ToString(row["DayOfMonth"]):"";txtRecipients.Text=Convert.ToString(row["Recipients"]);ddlFormat.SelectedValue=Convert.ToString(row["ExportFormat"]);litFormTitle.Text="Edit Schedule";btnSave.Text="Save Changes";btnCancel.Visible=true;return;}TimeSpan t=row["RunTime"]==DBNull.Value?TimeSpan.FromHours(8):(TimeSpan)row["RunTime"];int? day=row["DayOfWeek"]!=DBNull.Value?(int?)Convert.ToInt32(row["DayOfWeek"]):row["DayOfMonth"]!=DBNull.Value?(int?)Convert.ToInt32(row["DayOfMonth"]):null;DateTime next=Next(Convert.ToString(row["Frequency"]),t,day,DateTime.Now);bool ok=false;string action="";if(e.CommandName=="EnableSchedule"){ok=Repo.SetScheduleEnabled(id,true,next,CurrentUserId,CurrentRole);action="Schedule Enabled";}else if(e.CommandName=="DisableSchedule"){ok=Repo.SetScheduleEnabled(id,false,next,CurrentUserId,CurrentRole);action="Schedule Disabled";}else if(e.CommandName=="DeleteSchedule"){ok=Repo.DeleteSchedule(id,CurrentUserId,CurrentRole);action="Schedule Deleted";}if(ok)Audit(action,null,"Schedule",ReportAuthorization.Scheduled);Bind();}
 void ResetForm(){hidEditId.Value="";litFormTitle.Text="Create Schedule";btnSave.Text="Create Schedule";btnCancel.Visible=false;txtDay.Text="";txtRecipients.Text="";}
 void Msg(string m,bool ok){litMessage.Text="<div role='alert' class='s5-msg "+(ok?"s5-ok":"s5-error")+"'>"+ReportUi.Enc(m)+"</div>";}
}}
