<%@ Page Title="User & Security Reports | AQOONHUB SMS" Language="C#" MasterPageFile="~/MasterPages/MainMaster.master" AutoEventWireup="true" CodeBehind="SecurityReports.aspx.cs" Inherits="AQOONHUB_SMS.Modules.Reports.SecurityReports" %>
<asp:Content ID="h" ContentPlaceHolderID="head" runat="server">
<style>
.s-wrap{padding:1.25rem;max-width:1600px;margin:auto}.s-sum{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.s-card{padding:1rem}.s-card p:first-child{font-size:.7rem;font-weight:700;color:#64748b;text-transform:uppercase}.s-card p:last-child{font-size:1.55rem;font-weight:800}.cards{display:grid;grid-template-columns:1fr;gap:.85rem}.rc{display:block;padding:1rem;border:1px solid #e2e8f0;border-radius:12px;background:#fff;text-decoration:none;color:#0f172a;transition:.2s}.rc:hover{border-color:#2563eb;box-shadow:0 4px 12px rgba(37,99,235,.08)}.rc-t{font-size:.88rem;font-weight:700}.rc-d{font-size:.75rem;color:#64748b;margin-top:.25rem;min-height:2rem}.rc-a{font-size:.75rem;font-weight:700;color:#2563eb;margin-top:.6rem}.rc-off{opacity:.68}.rc-lock{font-size:.7rem}.sec-note{border:1px solid #c7d2fe;background:#eef2ff;color:#3730a3;border-radius:10px;padding:.75rem 1rem;font-size:.78rem}
@media(min-width:640px){.cards{grid-template-columns:repeat(2,1fr)}}@media(min-width:768px){.s-sum{grid-template-columns:repeat(4,1fr)}}@media(min-width:1100px){.cards{grid-template-columns:repeat(3,1fr)}}@media(min-width:1450px){.cards{grid-template-columns:repeat(4,1fr)}}
.dark .rc{background:#111c2e;border-color:#263449;color:#e5edf8}.dark .rc-d{color:#9fb0c8}.dark .sec-note{background:#1e1b4b;border-color:#4338ca;color:#c7d2fe}.rc:focus-visible{outline:3px solid #93c5fd;outline-offset:2px}@media(prefers-reduced-motion:reduce){.rc{transition:none}}
</style></asp:Content>
<asp:Content ID="b" ContentPlaceHolderID="MainContent" runat="server"><main class="s-wrap">
<nav class="flex gap-1.5 text-xs text-gray-500 dark:text-slate-400 mb-2" aria-label="Breadcrumb"><a href="~/Modules/Reports/Reports.aspx" runat="server">Reports</a><span>/</span><span>User &amp; Security</span></nav>
<div class="flex flex-wrap justify-between gap-3 mb-4"><div><h1 class="text-xl md:text-2xl font-bold">User &amp; Security Reports</h1><p class="text-sm text-gray-500 dark:text-slate-400 mt-1">Safe account, authentication and authorization reporting.</p></div><span class="badge bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-200 self-start">Restricted</span></div>
<div class="s-sum mb-4"><div class="card s-card"><p>Total users</p><p><asp:Literal ID="litUsers" runat="server" /></p></div><div class="card s-card"><p>Active</p><p class="text-emerald-600"><asp:Literal ID="litActive" runat="server" /></p></div><div class="card s-card"><p>Inactive</p><p class="text-amber-600"><asp:Literal ID="litInactive" runat="server" /></p></div><div class="card s-card"><p>Failed logins</p><p class="text-red-600"><asp:Literal ID="litFailed" runat="server" /></p></div></div>
<div class="sec-note mb-4" role="status"><strong>Data protection:</strong> Passwords, hashes, salts, reset tokens and authentication secrets are never selected, displayed, printed or exported.</div>
<asp:Panel ID="pnlError" runat="server" Visible="false" CssClass="card p-4 mb-4 text-sm text-amber-700 dark:text-amber-300" role="alert"><asp:Literal ID="litError" runat="server" /></asp:Panel>
<div class="cards"><asp:Literal ID="litCards" runat="server" /></div>
</main></asp:Content>
