//------------------------------------------------------------------------------
// <auto-generated></auto-generated>
//------------------------------------------------------------------------------
namespace AQOONHUB_SMS.Modules.Reports
{
    public partial class StudentReports
    {
        protected global::System.Web.UI.WebControls.Literal litDataSource;
        protected global::System.Web.UI.WebControls.Literal litCards;
    }
}
