using System;using System.Collections.Generic;using System.Data;using System.Linq;using System.Text;using System.Web;using System.Web.UI;using System.Web.UI.WebControls;
namespace AQOONHUB_SMS.Modules.Administration{public partial class Users:Page{readonly SystemRepository repo=new SystemRepository();int PageNo{get{return Math.Max(1,(int?)(ViewState["PageNo"])??1);}set{ViewState["PageNo"]=Math.Max(1,value);}}int TotalPages{get{return Math.Max(1,(int?)(ViewState["TotalPages"])??1);}set{ViewState["TotalPages"]=value;}}int Actor{get{int x;return int.TryParse(Convert.ToString(Session["UserID"]),out x)?x:0;}}
protected void Page_Load(object s,EventArgs e){SystemAuthorization.DemandAdmin(this);if(!IsPostBack){BindLists();Bind();}}
void BindLists(){DataTable roles=repo.Roles();ddlRole.Items.Add(new ListItem("All roles",""));foreach(DataRow x in roles.Rows){string n=x["RoleName"].ToString(),id=x["RoleID"].ToString();ddlRole.Items.Add(n);ddlNewRole.Items.Add(n);editRole.Items.Add(n);ddlAssignRole.Items.Add(new ListItem(n,id));ddlPermissionRole.Items.Add(new ListItem(n,id));}foreach(DataRow x in repo.Users("","","").Rows)ddlAssignUser.Items.Add(new ListItem(x["FullName"]+" — "+x["Email"],x["UserID"].ToString()));BindPermissions();}
void Bind(){int size=int.Parse(ddlPageSize.SelectedValue);PagedData p=repo.UsersPage(txtSearch.Text.Trim(),ddlRole.SelectedValue,ddlStatus.SelectedValue,PageNo,size);TotalPages=Math.Max(1,(int)Math.Ceiling(p.Total/(double)size));if(PageNo>TotalPages){PageNo=TotalPages;p=repo.UsersPage(txtSearch.Text.Trim(),ddlRole.SelectedValue,ddlStatus.SelectedValue,PageNo,size);}gvUsers.DataSource=p.Rows;gvUsers.DataBind();litPage.Text="Page "+PageNo+" of "+TotalPages+" · "+p.Total+" records";pgFirst.Enabled=pgPrev.Enabled=PageNo>1;pgNext.Enabled=pgLast.Enabled=PageNo<TotalPages;litTotal.Text=repo.UserCount("").ToString();litActive.Text=repo.UserCount("Active").ToString();litInactive.Text=repo.UserCount("Inactive").ToString();litRoles.Text=repo.Roles().Rows.Count.ToString();}
void BindPermissions(){if(ddlPermissionRole.Items.Count==0)return;int roleId=int.Parse(ddlPermissionRole.SelectedValue);DataTable t=repo.Permissions(roleId);gvPermissions.DataSource=t;gvPermissions.DataBind();string role=ddlPermissionRole.SelectedItem.Text;btnSavePermissions.Enabled=SystemAuthorization.Normalize(role)!="superadmin";}
protected void btnFilter_Click(object s,EventArgs e){PageNo=1;Bind();}protected void btnReset_Click(object s,EventArgs e){txtSearch.Text="";ddlRole.SelectedIndex=ddlStatus.SelectedIndex=0;PageNo=1;Bind();}protected void PageSizeChanged(object s,EventArgs e){PageNo=1;Bind();}protected void PageNav(object s,EventArgs e){string id=((Control)s).ID;if(id=="pgFirst")PageNo=1;else if(id=="pgPrev")PageNo--;else if(id=="pgNext")PageNo++;else PageNo=TotalPages;Bind();}
protected void gvUsers_RowCommand(object s,GridViewCommandEventArgs e){int id;if(!int.TryParse(Convert.ToString(e.CommandArgument),out id)||id<1){Error("Invalid user.");return;}try{DataRow u=repo.User(id);if(u==null)throw new InvalidOperationException("User not found.");if(e.CommandName=="ViewUser"){litDetails.Text=Detail("User ID",u["UserID"])+Detail("Full Name",u["FullName"])+Detail("Username","Unavailable")+Detail("Email",u["Email"])+Detail("Phone",u["Phone"])+Detail("Role",u["Role"])+Detail("Status",(bool)u["IsActive"]?"Active":"Inactive")+Detail("Created",u.Table.Columns.Contains("CreatedAt")?u["CreatedAt"]:"Unavailable")+Detail("Last Login",u["LastLogin"])+Detail("Department / Branch","Unavailable");pnlDetails.Visible=true;}else if(e.CommandName=="EditUser"){editId.Value=id.ToString();editName.Text=u["FullName"].ToString();editEmail.Text=u["Email"].ToString();editPhone.Text=u["Phone"].ToString();editRole.SelectedValue=u["Role"].ToString();editActive.Checked=(bool)u["IsActive"];pnlEdit.Visible=true;}else if(e.CommandName=="Deactivate"){repo.DeactivateUser(id,Actor);repo.Log(Actor,"USER_DEACTIVATED","Users","User account deactivated: ID "+id,Request.UserHostAddress);Success("User deactivated.");Bind();}}catch(Exception ex){Error(ex.GetBaseException().Message);}}
protected void btnUpdateUser_Click(object s,EventArgs e){try{int id;if(!int.TryParse(editId.Value,out id)||repo.User(id)==null)throw new InvalidOperationException("User not found.");Validate(editName.Text,editEmail.Text,editRole.SelectedValue,id);repo.UpdateUserSafe(id,editName.Text.Trim(),editEmail.Text.Trim(),editPhone.Text.Trim(),editRole.SelectedValue,editActive.Checked,Actor);repo.Log(Actor,"USER_UPDATED","Users","User account updated: ID "+id,Request.UserHostAddress);pnlEdit.Visible=false;Success("User updated successfully.");Bind();}catch(Exception ex){Error(ex.GetBaseException().Message);pnlEdit.Visible=true;}}
protected void CloseDetails(object s,EventArgs e){pnlDetails.Visible=false;}protected void CloseEdit(object s,EventArgs e){pnlEdit.Visible=false;}
protected void PermissionRoleChanged(object s,EventArgs e){BindPermissions();}protected void btnSavePermissions_Click(object s,EventArgs e){try{int roleId=int.Parse(ddlPermissionRole.SelectedValue);var ids=new List<int>();foreach(GridViewRow row in gvPermissions.Rows){var c=(CheckBox)row.FindControl("chkGranted");if(c.Checked)ids.Add(Convert.ToInt32(gvPermissions.DataKeys[row.RowIndex].Value));}repo.SavePermissions(roleId,ids);repo.Log(Actor,"PERMISSION_UPDATED","Roles","Permission mappings updated for role ID "+roleId,Request.UserHostAddress);Success("Permissions saved.");BindPermissions();}catch(Exception ex){Error(ex.GetBaseException().Message);}}
protected void btnAssign_Click(object s,EventArgs e){try{repo.AssignRole(int.Parse(ddlAssignUser.SelectedValue),int.Parse(ddlAssignRole.SelectedValue),Actor);repo.Log(Actor,"ROLE_ASSIGNED","Users","Role assigned to user",Request.UserHostAddress);Success("Role assigned.");Bind();}catch(Exception ex){Error(ex.GetBaseException().Message);}}
protected void btnSaveUser_Click(object s,EventArgs e){try{Validate(txtName.Text,txtEmail.Text,ddlNewRole.SelectedValue,null);if(txtPassword.Text.Length<8)throw new InvalidOperationException("Temporary password must contain at least 8 characters.");repo.SaveUser(null,txtName.Text.Trim(),txtEmail.Text.Trim(),txtPhone.Text.Trim(),ddlNewRole.SelectedValue,chkActive.Checked,SecurityHelper.HashPassword(txtPassword.Text));repo.Log(Actor,"USER_CREATED","Users","User account created",Request.UserHostAddress);Success("User created successfully.");Bind();}catch(Exception ex){Error(ex.GetBaseException().Message);}}
void Validate(string name,string email,string role,int? id){if(string.IsNullOrWhiteSpace(name)||name.Trim().Length<2)throw new InvalidOperationException("Full name is required.");if(!SecurityHelper.IsValidEmail(email.Trim()))throw new InvalidOperationException("Enter a valid email.");if(repo.EmailExists(email.Trim(),id))throw new InvalidOperationException("Email is already in use.");if(!repo.Roles().AsEnumerable().Any(x=>x["RoleName"].ToString()==role&&(bool)x["IsActive"]))throw new InvalidOperationException("Role is invalid.");}
protected void btnExport_Click(object s,EventArgs e){DataTable t=repo.Users(txtSearch.Text.Trim(),ddlRole.SelectedValue,ddlStatus.SelectedValue);var b=new StringBuilder("\uFEFFFull Name,Email,Phone,Role,Status,Last Login\r\n");foreach(DataRow r in t.Rows)b.AppendLine(Csv(r["FullName"])+","+Csv(r["Email"])+","+Csv(r["Phone"])+","+Csv(r["Role"])+","+Csv((bool)r["IsActive"]?"Active":"Inactive")+","+Csv(r["LastLogin"]));repo.Log(Actor,"USER_EXPORTED","Users","Filtered user list exported",Request.UserHostAddress);Response.Clear();Response.ContentType="text/csv";Response.AddHeader("Content-Disposition","attachment; filename=users-"+DateTime.Now.ToString("yyyyMMdd-HHmm")+".csv");Response.BinaryWrite(Encoding.UTF8.GetBytes(b.ToString()));Response.End();}
string Csv(object o){string v=Convert.ToString(o);if(v.StartsWith("=")||v.StartsWith("+")||v.StartsWith("-")||v.StartsWith("@"))v="'"+v;return "\""+v.Replace("\"","\"\"")+"\"";}string Detail(string k,object v){return "<div><dt>"+HttpUtility.HtmlEncode(k)+"</dt><dd>"+HttpUtility.HtmlEncode(v==null||v==DBNull.Value||string.IsNullOrWhiteSpace(Convert.ToString(v))?"Unavailable":Convert.ToString(v))+"</dd></div>";}void Success(string m){litMessage.Text="<div class='sys-note' role='status'>"+HttpUtility.HtmlEncode(m)+"</div>";}void Error(string m){litMessage.Text="<div class='sys-error' role='alert'>"+HttpUtility.HtmlEncode(m)+"</div>";}}
}
