//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class AttendanceSettings
    {
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Panel pnlReadOnly;
        protected global::System.Web.UI.WebControls.CheckBox chkAllowTeachers;
        protected global::System.Web.UI.WebControls.CheckBox chkAllowEdit;
        protected global::System.Web.UI.WebControls.TextBox txtEditWindow;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.TextBox txtLateAfter;
        protected global::System.Web.UI.WebControls.CheckBox chkExcusedRemarks;
        protected global::System.Web.UI.WebControls.CheckBox chkFuture;
        protected global::System.Web.UI.WebControls.CheckBox chkIncludeLate;
        protected global::System.Web.UI.WebControls.CheckBox chkExcludeExcused;
        protected global::System.Web.UI.WebControls.TextBox txtConsecutive;
        protected global::System.Web.UI.WebControls.TextBox txtLowThreshold;
        protected global::System.Web.UI.WebControls.CheckBox chkParent;
        protected global::System.Web.UI.WebControls.CheckBox chkEmail;
        protected global::System.Web.UI.WebControls.CheckBox chkSms;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    }
}
