//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class AttendanceAnalytics
    {
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSessionType;
        protected global::System.Web.UI.WebControls.Button btnView;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Literal litRate;
        protected global::System.Web.UI.WebControls.Literal litSessions;
        protected global::System.Web.UI.WebControls.Literal litStudents;
        protected global::System.Web.UI.WebControls.Literal litP;
        protected global::System.Web.UI.WebControls.Literal litA;
        protected global::System.Web.UI.WebControls.Literal litL;
        protected global::System.Web.UI.WebControls.Literal litE;
        protected global::System.Web.UI.WebControls.Literal litRisk;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlData;
        protected global::System.Web.UI.WebControls.GridView gvTop;
        protected global::System.Web.UI.WebControls.GridView gvAbsent;
        protected global::System.Web.UI.WebControls.GridView gvLate;
        protected global::System.Web.UI.WebControls.GridView gvRisk;
        protected global::System.Web.UI.WebControls.Literal litChartData;
    }
}
