//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class AttendanceByDate
    {
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSessionType;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnView;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.HyperLink lnkOpenMark;
        protected global::System.Web.UI.WebControls.Literal litFilterSummary;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litP;
        protected global::System.Web.UI.WebControls.Literal litA;
        protected global::System.Web.UI.WebControls.Literal litL;
        protected global::System.Web.UI.WebControls.Literal litE;
        protected global::System.Web.UI.WebControls.Literal litRate;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}
