//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class Attendance
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkSettings;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litPresent;
        protected global::System.Web.UI.WebControls.Literal litAbsent;
        protected global::System.Web.UI.WebControls.Literal litLate;
        protected global::System.Web.UI.WebControls.Literal litRate;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.GridView gvToday;
        protected global::System.Web.UI.WebControls.Literal litBP;
        protected global::System.Web.UI.WebControls.Literal litBA;
        protected global::System.Web.UI.WebControls.Literal litBL;
        protected global::System.Web.UI.WebControls.Literal litBE;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
        protected global::System.Web.UI.WebControls.GridView gvByClass;
    }
}
