//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class AttendanceAlerts
    {
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litNew;
        protected global::System.Web.UI.WebControls.Literal litReviewed;
        protected global::System.Web.UI.WebControls.Literal litResolved;
        protected global::System.Web.UI.WebControls.Literal litCritical;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gv;
        protected global::System.Web.UI.WebControls.Panel pnlResolve;
        protected global::System.Web.UI.WebControls.Literal litResolveId;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnResolveConfirm;
        protected global::System.Web.UI.WebControls.Button btnResolveCancel;
        protected global::System.Web.UI.WebControls.HiddenField hfResolveId;
    }
}
