//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Attendance
{
    public partial class ParentAttendance
    {
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.Panel pnlNoChildren;
        protected global::System.Web.UI.WebControls.Panel pnlBody;
        protected global::System.Web.UI.WebControls.DropDownList ddlChild;
        protected global::System.Web.UI.WebControls.TextBox txtMonth;
        protected global::System.Web.UI.WebControls.Literal litChildInfo;
        protected global::System.Web.UI.WebControls.Literal litPct;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litP;
        protected global::System.Web.UI.WebControls.Literal litA;
        protected global::System.Web.UI.WebControls.Literal litL;
        protected global::System.Web.UI.WebControls.Literal litE;
        protected global::System.Web.UI.WebControls.Panel pnlAlerts;
        protected global::System.Web.UI.WebControls.Repeater rptAlerts;
        protected global::System.Web.UI.WebControls.GridView gvRecent;
        protected global::System.Web.UI.WebControls.Literal litCalendar;
    }
}
