using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace AQOONHUB_SMS.Modules.Communication
{
    public sealed class CommPage { public DataTable Rows; public int Total; }
    public sealed class CommunicationRepository
    {
        readonly string cs=ConfigurationManager.ConnectionStrings["AQOONHUB_DB"].ConnectionString;
        SqlParameter P(string n,object v){return new SqlParameter(n,v??DBNull.Value);}
        public DataTable Q(string sql,params SqlParameter[] ps){using(var c=new SqlConnection(cs))using(var a=new SqlDataAdapter(sql,c)){if(ps!=null)a.SelectCommand.Parameters.AddRange(ps);var t=new DataTable();a.Fill(t);return t;}}
        public object S(string sql,params SqlParameter[] ps){using(var c=new SqlConnection(cs))using(var x=new SqlCommand(sql,c)){if(ps!=null)x.Parameters.AddRange(ps);c.Open();return x.ExecuteScalar();}}
        public int X(string sql,params SqlParameter[] ps){using(var c=new SqlConnection(cs))using(var x=new SqlCommand(sql,c)){if(ps!=null)x.Parameters.AddRange(ps);c.Open();return x.ExecuteNonQuery();}}
        public DataTable OverviewTotals(int uid){return Q(@"SELECT
 (SELECT COUNT(*) FROM dbo.Announcements) TotalAnnouncements,
 (SELECT COUNT(*) FROM dbo.MessageRecipients WHERE RecipientUserID=@u AND IsRead=0 AND DeletedByRecipient=0) UnreadMessages,
 (SELECT COUNT(*) FROM dbo.CommunicationDeliveries WHERE Channel='SMS' AND Status IN('Sent','Delivered','Read')) SmsSent,
 (SELECT COUNT(*) FROM dbo.CommunicationDeliveries WHERE Channel='Email' AND Status IN('Sent','Delivered','Read')) EmailsSent,
 (SELECT COUNT(*) FROM dbo.CommunicationDeliveries WHERE Status='Failed') FailedDeliveries",P("@u",uid));}
        public DataTable DeliveryTrend(){return Q(@"WITH d AS(SELECT CAST(DATEADD(day,-6,CAST(GETDATE() AS date)) AS date) D UNION ALL SELECT DATEADD(day,1,D) FROM d WHERE D<CAST(GETDATE() AS date)) SELECT d.D,SUM(CASE WHEN x.Status IN('Delivered','Read') THEN 1 ELSE 0 END) Delivered,SUM(CASE WHEN x.Status='Failed' THEN 1 ELSE 0 END) Failed FROM d LEFT JOIN dbo.CommunicationDeliveries x ON CAST(x.CreatedAt AS date)=d.D GROUP BY d.D ORDER BY d.D OPTION(MAXRECURSION 7)");}
        public DataTable ChannelTotals(){return Q("SELECT Channel,COUNT(*) Total FROM dbo.CommunicationDeliveries GROUP BY Channel ORDER BY Channel");}
        public DataTable StatusTotals(){return Q("SELECT Status,COUNT(*) Total FROM dbo.CommunicationDeliveries GROUP BY Status ORDER BY Status");}
        public DataTable Recent(){return Q(@"SELECT TOP 8 Kind,Title,CreatedAt FROM(SELECT 'Announcement' Kind,Title,CreatedAt FROM dbo.Announcements UNION ALL SELECT 'In-App Message',t.Subject,m.CreatedAt FROM dbo.Messages m JOIN dbo.MessageThreads t ON t.ThreadID=m.ThreadID UNION ALL SELECT d.Channel,COALESCE(d.Subject,d.MessagePreview),d.CreatedAt FROM dbo.CommunicationDeliveries d)x ORDER BY CreatedAt DESC");}
        public DataTable Upcoming(){return Q(@"SELECT TOP 8 Channel,COALESCE(Subject,LEFT(MessageBody,80)) Subject,ScheduleAt,Status FROM dbo.CommunicationCampaigns WHERE ScheduleAt>=GETDATE() AND Status IN('Pending','Pending Scheduler Configuration') UNION ALL SELECT TOP 8 'Announcement',Title,PublishDate,Status FROM dbo.Announcements WHERE PublishDate>=GETDATE() AND Status='Scheduled' ORDER BY ScheduleAt");}
        public CommPage Announcements(string search,string audience,string priority,string status,DateTime? from,DateTime? to,int page,int size){string w=@" WHERE (@q='' OR a.Title LIKE @like OR a.Body LIKE @like) AND (@aud='' OR a.AudienceType=@aud) AND (@pri='' OR a.Priority=@pri) AND (@st='' OR a.Status=@st) AND (@f IS NULL OR a.PublishDate>=@f) AND (@t IS NULL OR a.PublishDate<DATEADD(day,1,@t))";var ps=new[]{P("@q",search),P("@like","%"+search+"%"),P("@aud",audience),P("@pri",priority),P("@st",status),P("@f",from),P("@t",to)};int total=Convert.ToInt32(S("SELECT COUNT(*) FROM dbo.Announcements a"+w,ps));var list=new List<SqlParameter>();foreach(var p in ps)list.Add(P(p.ParameterName,p.Value));list.Add(P("@off",(page-1)*size));list.Add(P("@take",size));var rows=Q(@"SELECT a.AnnouncementID,a.Title,a.AudienceType Audience,a.Priority,COALESCE(u.FullName,'System') PublishedBy,a.PublishDate,a.ExpiryDate,a.Status,a.Body,(SELECT COUNT(*) FROM dbo.AnnouncementRecipients r WHERE r.AnnouncementID=a.AnnouncementID) RecipientCount,(SELECT COUNT(*) FROM dbo.AnnouncementRecipients r WHERE r.AnnouncementID=a.AnnouncementID AND r.IsRead=1) ReadCount FROM dbo.Announcements a LEFT JOIN dbo.Users u ON u.UserID=a.AuthorID"+w+" ORDER BY a.CreatedAt DESC OFFSET @off ROWS FETCH NEXT @take ROWS ONLY",list.ToArray());return new CommPage{Rows=rows,Total=total};}
        public DataRow Announcement(int id){var t=Q("SELECT TOP 1 AnnouncementID,Title,Body,Priority,AudienceType,TargetClassID,TargetSectionID,TargetRole,PublishDate,ExpiryDate,Status,IsPublished,AuthorID FROM dbo.Announcements WHERE AnnouncementID=@id",P("@id",id));return t.Rows.Count==0?null:t.Rows[0];}
        public int SaveAnnouncement(int? id,string title,string body,string priority,string audience,int? classId,int? sectionId,string role,int? selectedUser,DateTime? publish,DateTime? expiry,string status,int actor)
        {using(var c=new SqlConnection(cs)){c.Open();using(var tx=c.BeginTransaction()){try{var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=id.HasValue?@"UPDATE dbo.Announcements SET Title=@n,Body=@b,Priority=@p,Audience=@a,AudienceType=@a,TargetClassID=@c,TargetSectionID=@s,TargetRole=@r,PublishDate=@pub,ExpiryDate=@exp,Status=@st,IsPublished=CASE WHEN @st='Published' THEN 1 ELSE 0 END,UpdatedAt=SYSDATETIME() WHERE AnnouncementID=@id;SELECT @id":@"INSERT dbo.Announcements(Title,Body,Audience,AudienceType,Priority,TargetClassID,TargetSectionID,TargetRole,PublishDate,ExpiryDate,Status,IsPublished,AuthorID,CreatedAt)VALUES(@n,@b,@a,@a,@p,@c,@s,@r,@pub,@exp,@st,CASE WHEN @st='Published' THEN 1 ELSE 0 END,@u,GETDATE());SELECT CONVERT(int,SCOPE_IDENTITY())";cmd.Parameters.AddRange(new[]{P("@id",id),P("@n",title),P("@b",body),P("@p",priority),P("@a",audience),P("@c",classId),P("@s",sectionId),P("@r",role),P("@pub",publish),P("@exp",expiry),P("@st",status),P("@u",actor)});int aid=Convert.ToInt32(cmd.ExecuteScalar());cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="DELETE dbo.AnnouncementRecipients WHERE AnnouncementID=@id";cmd.Parameters.Add(P("@id",aid));cmd.ExecuteNonQuery();cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=@"INSERT dbo.AnnouncementRecipients(AnnouncementID,RecipientType,RecipientID,UserID) SELECT @id,@a,NULL,u.UserID FROM dbo.Users u WHERE u.IsActive=1 AND (@a='All Users' OR @a='Selected Users' AND u.UserID=@selected OR @a='Specific Role' AND REPLACE(REPLACE(REPLACE(LOWER(u.Role),' ',''),'_',''),'-','')=REPLACE(REPLACE(REPLACE(LOWER(@r),' ',''),'_',''),'-','') OR @a='Parents' AND REPLACE(LOWER(u.Role),' ','') IN('parent','guardian') OR @a='Teachers' AND LOWER(u.Role)='teacher' OR @a='Staff' AND EXISTS(SELECT 1 FROM dbo.Staff s WHERE s.UserID=u.UserID) OR @a IN('Specific Class','Specific Section') AND EXISTS(SELECT 1 FROM dbo.Guardians g JOIN dbo.Students st ON st.GuardianID=g.GuardianID WHERE g.UserID=u.UserID AND (@c IS NULL OR EXISTS(SELECT 1 FROM dbo.Sections z WHERE z.SectionID=st.SectionID AND z.ClassID=@c)) AND (@s IS NULL OR st.SectionID=@s)))";cmd.Parameters.AddRange(new[]{P("@id",aid),P("@a",audience),P("@r",role),P("@c",classId),P("@s",sectionId),P("@selected",selectedUser)});cmd.ExecuteNonQuery();if(audience=="Students"){cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT dbo.AnnouncementRecipients(AnnouncementID,RecipientType,RecipientID,UserID) SELECT @id,'Student',StudentID,NULL FROM dbo.Students WHERE Status='Active'";cmd.Parameters.Add(P("@id",aid));cmd.ExecuteNonQuery();}tx.Commit();return aid;}catch{tx.Rollback();throw;}}}}
        public bool SetAnnouncementStatus(int id,string status,int actor){return X("UPDATE dbo.Announcements SET Status=@s,IsPublished=CASE WHEN @s='Published' THEN 1 ELSE 0 END,PublishDate=CASE WHEN @s='Published' AND PublishDate IS NULL THEN SYSDATETIME() ELSE PublishDate END,UpdatedAt=SYSDATETIME() WHERE AnnouncementID=@id",P("@s",status),P("@id",id))==1;}
        public bool DeleteDraftAnnouncement(int id){return X("DELETE dbo.Announcements WHERE AnnouncementID=@id AND Status='Draft'",P("@id",id))==1;}
        public DataTable RecipientUsers(string role,int actor){string r=CommunicationAuthorization.Normalize(role);if(CommunicationAuthorization.IsAdmin(role))return Q("SELECT UserID,FullName,Email,Role FROM dbo.Users WHERE IsActive=1 AND UserID<>@u ORDER BY FullName",P("@u",actor));if(r=="parent"||r=="guardian")return Q("SELECT UserID,FullName,Email,Role FROM dbo.Users WHERE IsActive=1 AND REPLACE(LOWER(Role),' ','') IN('superadmin','admin','teacher') ORDER BY FullName");if(r=="teacher")return Q(@"SELECT DISTINCT u.UserID,u.FullName,u.Email,u.Role FROM dbo.Users u WHERE u.IsActive=1 AND (REPLACE(LOWER(u.Role),' ','') IN('superadmin','admin') OR u.UserID IN(SELECT g.UserID FROM dbo.Staff ts JOIN dbo.ClassSubjectTeachers cst ON cst.StaffID=ts.StaffID AND cst.IsActive=1 JOIN dbo.Students st ON st.SectionID=cst.SectionID AND st.Status='Active' JOIN dbo.Guardians g ON g.GuardianID=st.GuardianID WHERE ts.UserID=@u AND g.UserID IS NOT NULL)) ORDER BY u.FullName",P("@u",actor));if(r=="security")return Q("SELECT UserID,FullName,Email,Role FROM dbo.Users WHERE IsActive=1 AND REPLACE(LOWER(Role),' ','') IN('superadmin','admin','security') AND UserID<>@u ORDER BY FullName",P("@u",actor));if(r=="accountant")return Q("SELECT UserID,FullName,Email,Role FROM dbo.Users WHERE IsActive=1 AND REPLACE(LOWER(Role),' ','') IN('superadmin','admin','parent','guardian','student') AND UserID<>@u ORDER BY FullName",P("@u",actor));return Q("SELECT UserID,FullName,Email,Role FROM dbo.Users WHERE IsActive=1 AND REPLACE(LOWER(Role),' ','') IN('superadmin','admin','academic','registrar','teacher','parent','guardian','student') AND UserID<>@u ORDER BY FullName",P("@u",actor));}
        public long SaveMessage(long? thread,int sender,int recipient,string subject,string body,bool draft,string originalName,string storedName,string relativePath,string contentType,long fileSize){using(var c=new SqlConnection(cs)){c.Open();using(var tx=c.BeginTransaction()){try{if(thread.HasValue){var guard=c.CreateCommand();guard.Transaction=tx;guard.CommandText="IF NOT EXISTS(SELECT 1 FROM dbo.Messages m LEFT JOIN dbo.MessageRecipients r ON r.MessageID=m.MessageID WHERE m.ThreadID=@t AND (m.SenderUserID=@u OR r.RecipientUserID=@u)) THROW 51000,'Message thread access denied.',1";guard.Parameters.AddRange(new[]{P("@t",thread),P("@u",sender)});guard.ExecuteNonQuery();}else{var a=c.CreateCommand();a.Transaction=tx;a.CommandText="INSERT dbo.MessageThreads(Subject,CreatedByUserID)VALUES(@s,@u);SELECT CONVERT(bigint,SCOPE_IDENTITY())";a.Parameters.AddRange(new[]{P("@s",subject),P("@u",sender)});thread=Convert.ToInt64(a.ExecuteScalar());}var m=c.CreateCommand();m.Transaction=tx;m.CommandText="INSERT dbo.Messages(ThreadID,SenderUserID,Body,IsDraft)VALUES(@t,@u,@b,@d);SELECT CONVERT(bigint,SCOPE_IDENTITY())";m.Parameters.AddRange(new[]{P("@t",thread),P("@u",sender),P("@b",body),P("@d",draft)});long mid=Convert.ToInt64(m.ExecuteScalar());if(!draft){m=c.CreateCommand();m.Transaction=tx;m.CommandText="INSERT dbo.MessageRecipients(MessageID,RecipientUserID)VALUES(@m,@r);UPDATE dbo.MessageThreads SET LastMessageAt=SYSDATETIME() WHERE ThreadID=@t";m.Parameters.AddRange(new[]{P("@m",mid),P("@r",recipient),P("@t",thread)});m.ExecuteNonQuery();}if(!string.IsNullOrEmpty(storedName)){m=c.CreateCommand();m.Transaction=tx;m.CommandText="INSERT dbo.CommunicationAttachments(MessageID,OriginalFileName,StoredFileName,RelativePath,ContentType,FileSize,UploadedByUserID)VALUES(@m,@o,@s,@p,@c,@z,@u)";m.Parameters.AddRange(new[]{P("@m",mid),P("@o",originalName),P("@s",storedName),P("@p",relativePath),P("@c",contentType),P("@z",fileSize),P("@u",sender)});m.ExecuteNonQuery();}tx.Commit();return mid;}catch{tx.Rollback();throw;}}}}
        public CommPage Messages(int uid,string tab,string search,string status,int page,int size){string mode=tab=="sent"?"m.SenderUserID=@u AND m.IsDraft=0":tab=="drafts"?"m.SenderUserID=@u AND m.IsDraft=1":tab=="archived"?"r.RecipientUserID=@u AND r.IsArchived=1":"r.RecipientUserID=@u AND r.IsArchived=0 AND r.DeletedByRecipient=0";string w=" WHERE "+mode+" AND (@q='' OR t.Subject LIKE @like OR m.Body LIKE @like) AND (@st='' OR @st=CASE WHEN m.IsDraft=1 THEN 'Draft' WHEN r.IsRead=0 THEN 'Unread' ELSE 'Read' END)";var ps=new[]{P("@u",uid),P("@q",search),P("@like","%"+search+"%"),P("@st",status)};string from=" FROM dbo.Messages m JOIN dbo.MessageThreads t ON t.ThreadID=m.ThreadID LEFT JOIN dbo.MessageRecipients r ON r.MessageID=m.MessageID LEFT JOIN dbo.Users s ON s.UserID=m.SenderUserID LEFT JOIN dbo.Users ru ON ru.UserID=r.RecipientUserID";int total=Convert.ToInt32(S("SELECT COUNT(DISTINCT m.MessageID)"+from+w,ps));var pp=new List<SqlParameter>();foreach(var p in ps)pp.Add(P(p.ParameterName,p.Value));pp.Add(P("@o",(page-1)*size));pp.Add(P("@z",size));var rows=Q("SELECT DISTINCT m.MessageID,m.ThreadID,t.Subject,CASE WHEN m.SenderUserID=@u THEN COALESCE(ru.FullName,'Draft') ELSE s.FullName END Person,LEFT(m.Body,140) Preview,m.CreatedAt,CASE WHEN m.IsDraft=1 THEN 'Draft' WHEN r.IsArchived=1 THEN 'Archived' WHEN r.IsRead=0 THEN 'Unread' ELSE 'Read' END Status"+from+w+" ORDER BY m.CreatedAt DESC OFFSET @o ROWS FETCH NEXT @z ROWS ONLY",pp.ToArray());return new CommPage{Rows=rows,Total=total};}
        public DataTable Thread(long id,int uid){return Q(@"IF NOT EXISTS(SELECT 1 FROM dbo.Messages m LEFT JOIN dbo.MessageRecipients r ON r.MessageID=m.MessageID WHERE m.ThreadID=@t AND (m.SenderUserID=@u OR r.RecipientUserID=@u)) THROW 51000,'Message thread access denied.',1; UPDATE r SET IsRead=1,ReadAt=COALESCE(ReadAt,SYSDATETIME()) FROM dbo.MessageRecipients r JOIN dbo.Messages m ON m.MessageID=r.MessageID WHERE m.ThreadID=@t AND r.RecipientUserID=@u;SELECT m.MessageID,t.Subject,s.FullName Sender,m.Body,m.CreatedAt,CASE WHEN r.IsRead=1 THEN 'Read' ELSE 'Unread' END ReadState FROM dbo.Messages m JOIN dbo.MessageThreads t ON t.ThreadID=m.ThreadID JOIN dbo.Users s ON s.UserID=m.SenderUserID LEFT JOIN dbo.MessageRecipients r ON r.MessageID=m.MessageID AND r.RecipientUserID=@u WHERE m.ThreadID=@t AND m.IsDraft=0 ORDER BY m.CreatedAt",P("@t",id),P("@u",uid));}
        public DataTable MessageAttachments(long messageId,int uid){return Q(@"IF NOT EXISTS(SELECT 1 FROM dbo.Messages m LEFT JOIN dbo.MessageRecipients r ON r.MessageID=m.MessageID WHERE m.MessageID=@m AND (m.SenderUserID=@u OR r.RecipientUserID=@u)) THROW 51000,'Attachment access denied.',1; SELECT AttachmentID,OriginalFileName,ContentType,FileSize FROM dbo.CommunicationAttachments WHERE MessageID=@m ORDER BY AttachmentID",P("@m",messageId),P("@u",uid));}
        public DataTable AnnouncementAttachments(int announcementId,int uid,string role){string admin=CommunicationAuthorization.IsAdmin(role)?"1":"0";return Q(@"IF NOT EXISTS(SELECT 1 FROM dbo.Announcements a WHERE a.AnnouncementID=@a AND (@admin=1 OR a.AuthorID=@u OR EXISTS(SELECT 1 FROM dbo.AnnouncementRecipients r WHERE r.AnnouncementID=a.AnnouncementID AND r.UserID=@u))) THROW 51000,'Attachment access denied.',1; SELECT AttachmentID,OriginalFileName,ContentType,FileSize FROM dbo.CommunicationAttachments WHERE AnnouncementID=@a ORDER BY AttachmentID",P("@a",announcementId),P("@u",uid),P("@admin",admin));}
        public DataRow AuthorizedAttachment(long attachmentId,int uid,string role){string admin=CommunicationAuthorization.IsAdmin(role)?"1":"0";var t=Q(@"SELECT TOP 1 ca.AttachmentID,ca.OriginalFileName,ca.StoredFileName,ca.RelativePath,ca.ContentType,ca.FileSize FROM dbo.CommunicationAttachments ca LEFT JOIN dbo.Announcements a ON a.AnnouncementID=ca.AnnouncementID LEFT JOIN dbo.Messages m ON m.MessageID=ca.MessageID LEFT JOIN dbo.MessageRecipients mr ON mr.MessageID=m.MessageID AND mr.RecipientUserID=@u WHERE ca.AttachmentID=@id AND ((ca.AnnouncementID IS NOT NULL AND (@admin=1 OR a.AuthorID=@u OR EXISTS(SELECT 1 FROM dbo.AnnouncementRecipients ar WHERE ar.AnnouncementID=a.AnnouncementID AND ar.UserID=@u))) OR (ca.MessageID IS NOT NULL AND (m.SenderUserID=@u OR mr.RecipientUserID=@u)))",P("@id",attachmentId),P("@u",uid),P("@admin",admin));return t.Rows.Count==0?null:t.Rows[0];}
        public int ArchiveMessage(long id,int uid){return X("UPDATE r SET IsArchived=1 FROM dbo.MessageRecipients r WHERE r.MessageID=@m AND r.RecipientUserID=@u",P("@m",id),P("@u",uid));}
        public int SetMessageRead(long id,int uid,bool read){return X("UPDATE dbo.MessageRecipients SET IsRead=@r,ReadAt=CASE WHEN @r=1 THEN COALESCE(ReadAt,SYSDATETIME()) ELSE NULL END WHERE MessageID=@m AND RecipientUserID=@u",P("@r",read),P("@m",id),P("@u",uid));}
        public int DeleteMessageForRecipient(long id,int uid){return X("UPDATE dbo.MessageRecipients SET DeletedByRecipient=1 WHERE MessageID=@m AND RecipientUserID=@u",P("@m",id),P("@u",uid));}
        public DataTable Templates(){return Q("SELECT TemplateID,Name,Channel,Category,SubjectTemplate,BodyTemplate,IsActive,CreatedAt FROM dbo.CommunicationTemplates ORDER BY CreatedAt DESC");}
        public int SaveTemplate(string name,string channel,string category,string subject,string body,int actor){return Convert.ToInt32(S("INSERT dbo.CommunicationTemplates(Name,Channel,Category,SubjectTemplate,BodyTemplate,CreatedByUserID)VALUES(@n,@c,@g,@s,@b,@u);SELECT SCOPE_IDENTITY()",P("@n",name),P("@c",channel),P("@g",category),P("@s",subject),P("@b",body),P("@u",actor)));}
        public long SaveCampaign(long? id,string channel,string subject,string body,string audience,string value,DateTime? schedule,bool draft,int actor,string role){string st=draft?"Draft":schedule.HasValue?"Pending Scheduler Configuration":"Pending";if(!id.HasValue)return Convert.ToInt64(S("INSERT dbo.CommunicationCampaigns(Channel,Subject,MessageBody,AudienceType,AudienceValue,ScheduleAt,Status,CreatedByUserID)VALUES(@c,@s,@b,@a,@v,@d,@st,@u);SELECT SCOPE_IDENTITY()",P("@c",channel),P("@s",subject),P("@b",body),P("@a",audience),P("@v",value),P("@d",schedule),P("@st",st),P("@u",actor)));string own=CommunicationAuthorization.IsAdmin(role)?"":" AND CreatedByUserID=@u";int n=X("UPDATE dbo.CommunicationCampaigns SET Channel=@c,Subject=@s,MessageBody=@b,AudienceType=@a,AudienceValue=@v,ScheduleAt=@d,Status=@st,UpdatedAt=SYSDATETIME() WHERE CampaignID=@id AND Status IN('Draft','Pending','Pending Scheduler Configuration')"+own,P("@c",channel),P("@s",subject),P("@b",body),P("@a",audience),P("@v",value),P("@d",schedule),P("@st",st),P("@u",actor),P("@id",id));if(n!=1)throw new InvalidOperationException("Campaign cannot be edited because it is missing, processing, completed, cancelled, or not owned by you.");return id.Value;}
        public DataRow EditableCampaign(long id,int actor,string role){string own=CommunicationAuthorization.IsAdmin(role)?"":" AND CreatedByUserID=@u";var t=Q("SELECT TOP 1 CampaignID,Channel,Subject,MessageBody,AudienceType,AudienceValue,ScheduleAt,Status FROM dbo.CommunicationCampaigns WHERE CampaignID=@id AND Status IN('Draft','Pending','Pending Scheduler Configuration')"+own,P("@id",id),P("@u",actor));return t.Rows.Count==0?null:t.Rows[0];}
        public DataTable Campaigns(bool scheduled){return Q("SELECT c.CampaignID,c.Subject,c.Channel,c.AudienceType Audience,c.RecipientCount,u.FullName CreatedBy,c.ScheduleAt,c.Status FROM dbo.CommunicationCampaigns c JOIN dbo.Users u ON u.UserID=c.CreatedByUserID WHERE (@s=0 OR c.ScheduleAt IS NOT NULL) ORDER BY c.CreatedAt DESC",P("@s",scheduled));}
        public CommPage Deliveries(DateTime? from,DateTime? to,string channel,string status,string sender,string recipient,string search,int page,int size,int uid,string role){string own=CommunicationAuthorization.IsAdmin(role)?"":" AND d.CreatedByUserID=@u";string w=@" WHERE (@f IS NULL OR d.CreatedAt>=@f) AND (@t IS NULL OR d.CreatedAt<DATEADD(day,1,@t)) AND (@c='' OR d.Channel=@c) AND (@s='' OR d.Status=@s) AND (@sender='' OR cu.FullName LIKE @slike) AND (@recipient='' OR d.RecipientAddress LIKE @rlike) AND (@q='' OR d.Subject LIKE @qlike OR d.MessagePreview LIKE @qlike OR d.ProviderReference LIKE @qlike)"+own;var ps=new[]{P("@f",from),P("@t",to),P("@c",channel),P("@s",status),P("@sender",sender),P("@slike","%"+sender+"%"),P("@recipient",recipient),P("@rlike","%"+recipient+"%"),P("@q",search),P("@qlike","%"+search+"%"),P("@u",uid)};string fromSql=" FROM dbo.CommunicationDeliveries d JOIN dbo.Users cu ON cu.UserID=d.CreatedByUserID";int total=Convert.ToInt32(S("SELECT COUNT(*)"+fromSql+w,ps));var pp=new List<SqlParameter>();foreach(var p in ps)pp.Add(P(p.ParameterName,p.Value));pp.Add(P("@o",(page-1)*size));pp.Add(P("@z",size));var rows=Q("SELECT d.DeliveryID,d.RecipientAddress Recipient,d.Channel,COALESCE(d.Subject,d.MessagePreview) Subject,cu.FullName SentBy,d.SentAt,d.Status,d.DeliveredAt,d.FailureReason"+fromSql+w+" ORDER BY d.CreatedAt DESC OFFSET @o ROWS FETCH NEXT @z ROWS ONLY",pp.ToArray());return new CommPage{Rows=rows,Total=total};}
        public DataRow Delivery(long id,int uid,string role){string own=CommunicationAuthorization.IsAdmin(role)?"":" AND d.CreatedByUserID=@u";var t=Q("SELECT TOP 1 d.DeliveryID,d.CampaignID,d.RecipientAddress,d.Channel,d.Subject,d.MessagePreview,d.ProviderName,d.ProviderReference,d.Status,d.AttemptCount,d.SentAt,d.DeliveredAt,d.ReadAt,d.FailureReason,u.FullName CreatedBy,d.CreatedAt FROM dbo.CommunicationDeliveries d JOIN dbo.Users u ON u.UserID=d.CreatedByUserID WHERE d.DeliveryID=@id"+own,P("@id",id),P("@u",uid));return t.Rows.Count==0?null:t.Rows[0];}
        public void Log(int? uid,string action,string detail,string ip){X("INSERT dbo.AuditLog(UserID,Action,Module,Detail,IPAddress,ActionTime)VALUES(@u,@a,'Communication',@d,@ip,GETDATE())",P("@u",uid),P("@a",action),P("@d",detail),P("@ip",ip));}
    }
}
