using System;using System.Data;using System.IO;using System.Web.UI.WebControls;
namespace AQOONHUB_SMS.Modules.Communication{
public partial class Messages:CommunicationPageBase{
string Folder{get{return Convert.ToString(ViewState["Folder"]??"inbox");}set{ViewState["Folder"]=value;}}int P{get{return (int?)(ViewState["P"])??1;}set{ViewState["P"]=Math.Max(1,value);}}int Pages{get{return (int?)(ViewState["Pages"])??1;}set{ViewState["Pages"]=Math.Max(1,value);}}
protected void Page_Load(object s,EventArgs e){btnCompose.Visible=!CommunicationAuthorization.IsParent(Role);if(!IsPostBack){LoadRecipients();Bind();if(Request.QueryString["compose"]=="1")OpenCompose(null);}}
void LoadRecipients(){DataTable d=Repo.RecipientUsers(Role,UserId);ddlRecipient.DataSource=d;ddlRecipient.DataTextField="FullName";ddlRecipient.DataValueField="UserID";ddlRecipient.DataBind();if(d.Rows.Count==0)ddlRecipient.Items.Add(new ListItem("No authorized recipients",""));}
void Bind(){try{int z=PageSize(ddlPageSize.SelectedValue);CommPage x=Repo.Messages(UserId,Folder,txtSearch.Text.Trim(),ddlStatus.SelectedValue,P,z);Pages=Math.Max(1,(int)Math.Ceiling(x.Total/(double)z));if(P>Pages){P=Pages;Bind();return;}gv.DataSource=x.Rows;gv.DataBind();litPage.Text="Page "+P+" of "+Pages+" · "+x.Total+" records";btnPrev.Enabled=P>1;btnNext.Enabled=P<Pages;foreach(LinkButton b in new[]{tabInbox,tabSent,tabDrafts,tabArchived})b.CssClass="comm-tab";(Folder=="sent"?tabSent:Folder=="drafts"?tabDrafts:Folder=="archived"?tabArchived:tabInbox).CssClass="comm-tab active";}catch(Exception){Error("Messages are unavailable. Confirm the Communication migration and database connection.");}}
protected void Tab_Click(object s,EventArgs e){Folder=((LinkButton)s).CommandArgument;P=1;Bind();}protected void btnFilter_Click(object s,EventArgs e){P=1;Bind();}protected void btnReset_Click(object s,EventArgs e){txtSearch.Text="";ddlStatus.SelectedIndex=0;P=1;Bind();}protected void btnPrev_Click(object s,EventArgs e){P--;Bind();}protected void btnNext_Click(object s,EventArgs e){P++;Bind();}protected void PageSize_Changed(object s,EventArgs e){P=1;Bind();}
protected void btnCompose_Click(object s,EventArgs e){CommunicationAuthorization.Demand(this,r=>!CommunicationAuthorization.IsParent(r));OpenCompose(null);}void OpenCompose(long? thread){hidThread.Value=thread.HasValue?thread.ToString():"";txtSubject.Text=txtBody.Text="";pnlCompose.Visible=true;}
void Save(bool draft){string physical=null;try{int rid;if(!int.TryParse(ddlRecipient.SelectedValue,out rid))throw new InvalidOperationException("No authorized recipient is selected.");if(Repo.RecipientUsers(Role,UserId).Select("UserID="+rid).Length==0)throw new UnauthorizedAccessException("Recipient is not permitted for your role.");ValidateText(txtSubject.Text,txtBody.Text);long? t=string.IsNullOrEmpty(hidThread.Value)?(long?)null:Convert.ToInt64(hidThread.Value);if(CommunicationAuthorization.IsParent(Role)&&!t.HasValue)throw new UnauthorizedAccessException("Parents may reply only within permitted threads.");string original=null,stored=null,relative=null,mime=null;long size=0;if(upload.HasFile){ValidateUpload(upload,out original,out stored,out relative,out physical,out mime,out size);upload.SaveAs(physical);}long mid=Repo.SaveMessage(t,UserId,rid,txtSubject.Text.Trim(),txtBody.Text.Trim(),draft,original,stored,relative,mime,size);if(!draft)Repo.Log(UserId,"MESSAGE_SENT","In-app message "+mid+" sent to one authorized recipient; body omitted",Ip);pnlCompose.Visible=false;Success(draft?"Draft saved.":"Message sent.");Folder=draft?"drafts":"sent";Bind();}catch(Exception ex){if(!string.IsNullOrEmpty(physical)&&File.Exists(physical))File.Delete(physical);Error(ex.GetBaseException().Message);pnlCompose.Visible=true;}}
void ValidateUpload(FileUpload f,out string original,out string stored,out string relative,out string physical,out string mime,out long size){original=Path.GetFileName(f.FileName);string ext=Path.GetExtension(original).ToLowerInvariant();string[] exts={".pdf",".docx",".xlsx",".jpg",".jpeg",".png"};string[] mimes={"application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","image/jpeg","image/png"};mime=(f.PostedFile.ContentType??"").ToLowerInvariant();size=f.PostedFile.ContentLength;if(Array.IndexOf(exts,ext)<0||Array.IndexOf(mimes,mime)<0)throw new InvalidOperationException("Attachment type is not allowed.");if(size<=0||size>5*1024*1024)throw new InvalidOperationException("Attachment must be between 1 byte and 5 MB.");stored=Guid.NewGuid().ToString("N")+ext;relative="~/Uploads/Communication/"+stored;string root=Path.GetFullPath(Server.MapPath("~/Uploads/Communication/"));Directory.CreateDirectory(root);physical=Path.GetFullPath(Path.Combine(root,stored));if(!physical.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Attachment path is invalid.");}
protected void btnSaveDraft_Click(object s,EventArgs e){Save(true);}protected void btnSend_Click(object s,EventArgs e){Save(false);}protected void btnComposeClose_Click(object s,EventArgs e){pnlCompose.Visible=false;}
protected void gv_RowCommand(object s,GridViewCommandEventArgs e){long id;if(!long.TryParse(Convert.ToString(e.CommandArgument),out id))return;if(e.CommandName=="DeleteMessage"){Repo.DeleteMessageForRecipient(id,UserId);Bind();return;}if(e.CommandName=="UnreadMessage"){Repo.SetMessageRead(id,UserId,false);Bind();return;}if(e.CommandName=="ArchiveMessage"){Repo.ArchiveMessage(id,UserId);Repo.Log(UserId,"MESSAGE_ARCHIVED","Message "+id+" archived",Ip);Bind();return;}DataTable d=Repo.Thread(id,UserId);if(e.CommandName=="ForwardThread"){OpenCompose(null);if(d.Rows.Count>0)txtSubject.Text="Fwd: "+Convert.ToString(d.Rows[0]["Subject"]);return;}if(e.CommandName=="ReplyThread"){OpenCompose(id);if(d.Rows.Count>0)txtSubject.Text=Convert.ToString(d.Rows[0]["Subject"]);return;}rpThread.DataSource=d;rpThread.DataBind();litThreadTitle.Text=d.Rows.Count==0?"Message Thread":H(d.Rows[0]["Subject"]);pnlThread.Visible=true;}
protected string AttachmentLinks(object messageId){DataTable t=Repo.MessageAttachments(Convert.ToInt64(messageId),UserId);if(t.Rows.Count==0)return "";var b=new System.Text.StringBuilder("<div class='comm-attachments'><b>Attachments:</b>");foreach(DataRow r in t.Rows)b.Append(" <a class='btn btn-secondary' href='AttachmentDownload.aspx?id=").Append(r["AttachmentID"]).Append("'>Download ").Append(H(r["OriginalFileName"])).Append("</a>");return b.Append("</div>").ToString();}
protected void btnThreadClose_Click(object s,EventArgs e){pnlThread.Visible=false;}void Success(string m){litMessage.Text="<div class='comm-note' role='status'>"+H(m)+"</div>";}void Error(string m){litMessage.Text="<div class='comm-error' role='alert'>"+H(m)+"</div>";}
}}
