//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class Academics
    {
        protected global::System.Web.UI.WebControls.Literal litActiveYear;
        protected global::System.Web.UI.WebControls.Literal litClasses;
        protected global::System.Web.UI.WebControls.Literal litSections;
        protected global::System.Web.UI.WebControls.Literal litSubjects;
        protected global::System.Web.UI.WebControls.Literal litTeachers;
        protected global::System.Web.UI.WebControls.Literal litDistribution;
        protected global::System.Web.UI.WebControls.Panel pnlNoDist;
        protected global::System.Web.UI.WebControls.Repeater rptEvents;
        protected global::System.Web.UI.WebControls.Panel pnlNoEvents;
    }
}
