//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class ClassesSections
    {
        protected global::System.Web.UI.WebControls.Button btnAddClass;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlYearFilter;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Repeater rptClasses;
        protected global::System.Web.UI.WebControls.Panel pnlNoClasses;
        protected global::System.Web.UI.WebControls.Panel pnlSections;
        protected global::System.Web.UI.WebControls.Literal litSelClass;
        protected global::System.Web.UI.WebControls.Button btnAddSection;
        protected global::System.Web.UI.WebControls.GridView gvSections;
        protected global::System.Web.UI.WebControls.Literal litTotClasses;
        protected global::System.Web.UI.WebControls.Literal litTotSections;
        protected global::System.Web.UI.WebControls.Literal litTotStudents;
        protected global::System.Web.UI.WebControls.Literal litOccupancy;

        // Class drawer
        protected global::System.Web.UI.WebControls.Panel pnlClassDrawer;
        protected global::System.Web.UI.WebControls.Literal litClassTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseClass;
        protected global::System.Web.UI.WebControls.HiddenField hfClassId;
        protected global::System.Web.UI.WebControls.TextBox txtClassName;
        protected global::System.Web.UI.WebControls.TextBox txtClassCode;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevel;
        protected global::System.Web.UI.WebControls.TextBox txtClassCapacity;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassStatus;
        protected global::System.Web.UI.WebControls.Button btnCancelClass;
        protected global::System.Web.UI.WebControls.Button btnSaveClass;

        // Section drawer
        protected global::System.Web.UI.WebControls.Panel pnlSectionDrawer;
        protected global::System.Web.UI.WebControls.Literal litSectionTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseSection;
        protected global::System.Web.UI.WebControls.HiddenField hfSectionId;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionClass;
        protected global::System.Web.UI.WebControls.TextBox txtSectionName;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionTeacher;
        protected global::System.Web.UI.WebControls.TextBox txtSectionRoom;
        protected global::System.Web.UI.WebControls.TextBox txtSectionCapacity;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionStatus;
        protected global::System.Web.UI.WebControls.Button btnCancelSection;
        protected global::System.Web.UI.WebControls.Button btnSaveSection;
    }
}
