//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class Promotions
    {
        protected global::System.Web.UI.WebControls.Button btnPromote;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlFrom;
        protected global::System.Web.UI.WebControls.DropDownList ddlTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litEligible;
        protected global::System.Web.UI.WebControls.Literal litPromoted;
        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litRepeated;
        protected global::System.Web.UI.WebControls.Literal litGraduated;
        protected global::System.Web.UI.WebControls.Literal litNotEligible;
        protected global::System.Web.UI.WebControls.GridView gv;

        // Wizard
        protected global::System.Web.UI.WebControls.Panel pnlWizard;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseWiz;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl s1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl s2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl s3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl s4;
        protected global::System.Web.UI.WebControls.Panel pnlWizMsg;
        protected global::System.Web.UI.WebControls.Literal wizMsgText;

        protected global::System.Web.UI.WebControls.Panel pnlStep1;
        protected global::System.Web.UI.WebControls.DropDownList wFrom;
        protected global::System.Web.UI.WebControls.DropDownList wTo;
        protected global::System.Web.UI.WebControls.DropDownList wCurClass;
        protected global::System.Web.UI.WebControls.DropDownList wCurSection;
        protected global::System.Web.UI.WebControls.DropDownList wTgtClass;
        protected global::System.Web.UI.WebControls.DropDownList wTgtSection;
        protected global::System.Web.UI.WebControls.DropDownList wDefault;
        protected global::System.Web.UI.WebControls.Button btnStep1Next;

        protected global::System.Web.UI.WebControls.Panel pnlStep2;
        protected global::System.Web.UI.WebControls.CheckBox chkAll;
        protected global::System.Web.UI.WebControls.GridView gvReview;
        protected global::System.Web.UI.WebControls.Button btnStep2Back;
        protected global::System.Web.UI.WebControls.Button btnStep2Next;

        protected global::System.Web.UI.WebControls.Panel pnlStep3;
        protected global::System.Web.UI.WebControls.Literal litConfirm;
        protected global::System.Web.UI.WebControls.Button btnStep3Back;
        protected global::System.Web.UI.WebControls.Button btnConfirm;

        protected global::System.Web.UI.WebControls.Panel pnlStep4;
        protected global::System.Web.UI.WebControls.Literal litComplete;
        protected global::System.Web.UI.WebControls.Button btnViewList;
    }
}
