//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class Subjects
    {
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlTypeFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlClassFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gv;

        // Subject drawer
        protected global::System.Web.UI.WebControls.Panel pnlDrawer;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnClose;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.TextBox txtCode;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.TextBox txtMax;
        protected global::System.Web.UI.WebControls.TextBox txtPass;
        protected global::System.Web.UI.WebControls.DropDownList ddlActive;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSave;

        // Assign drawer
        protected global::System.Web.UI.WebControls.Panel pnlAssign;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseAssign;
        protected global::System.Web.UI.WebControls.HiddenField hfAssignSubject;
        protected global::System.Web.UI.WebControls.Literal litAssignSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignYear;
        protected global::System.Web.UI.WebControls.TextBox txtAssignPeriods;
        protected global::System.Web.UI.WebControls.Button btnCancelAssign;
        protected global::System.Web.UI.WebControls.Button btnSaveAssign;
    }
}
