//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class TeacherAssignments
    {
        protected global::System.Web.UI.WebControls.Button btnAssign;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlFYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlFClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlFSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlFTeacher;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gv;

        protected global::System.Web.UI.WebControls.Panel pnlDrawer;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnClose;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlTeacher;
        protected global::System.Web.UI.WebControls.TextBox txtPeriods;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
