//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQOONHUB_SMS.Modules.Academic
{
    public partial class Timetable
    {
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.Button btnAddEntry;
        protected global::System.Web.UI.WebControls.Panel msg;
        protected global::System.Web.UI.WebControls.Literal msgText;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.DropDownList ddlSection;
        protected global::System.Web.UI.WebControls.LinkButton btnWeekly;
        protected global::System.Web.UI.WebControls.LinkButton btnList;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnViewTimetable;
        protected global::System.Web.UI.WebControls.Literal litContext;
        protected global::System.Web.UI.WebControls.Panel pnlWeekly;
        protected global::System.Web.UI.WebControls.Literal litWeekly;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.GridView gvList;

        // Drawer
        protected global::System.Web.UI.WebControls.Panel pnlDrawer;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnClose;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.DropDownList dYear;
        protected global::System.Web.UI.WebControls.DropDownList dTerm;
        protected global::System.Web.UI.WebControls.DropDownList dClass;
        protected global::System.Web.UI.WebControls.DropDownList dSection;
        protected global::System.Web.UI.WebControls.DropDownList dSubject;
        protected global::System.Web.UI.WebControls.TextBox dTeacher;
        protected global::System.Web.UI.WebControls.HiddenField hfStaffId;
        protected global::System.Web.UI.WebControls.DropDownList dDay;
        protected global::System.Web.UI.WebControls.TextBox dPeriod;
        protected global::System.Web.UI.WebControls.TextBox dStart;
        protected global::System.Web.UI.WebControls.TextBox dEnd;
        protected global::System.Web.UI.WebControls.TextBox dRoom;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
